### ISSUE TITLE
Feature Request/Estimate - nested_fields as a tuple instead of a Boolean

### ISSUE THREAD

**Issue by atomboulian** [eamigo86/graphene-django-extras#52]
Hi @eamigo86 , thanks for this great library!!!

Can I make a suggestion?

For our mutations, we have some fields that we would like to pass the Foreign Key ID as an update instead of creating a new object, and some fields that we would like to create a new object through a nested structure. In other words, for some fields we want the result of `nested_fields` = True (nested object creation), and other fields we want the result of `nested_fields` = False (IDs passed in).

Do you think it would be better instead of passing a boolean for the nested_fields, pass a list of fields, to allow only nesting the fields that you specify in DjangoSerializerMutation? Similar to `only_fields`?

For example, below for the Foreign Key of Project and the related_name of "products":

```
class RoomSerializerMutation(DjangoSerializerMutation):

    class Meta:
        serializer_class = RoomSerializer
        nested_fields = ("project", "products", )
```
All other Foreign Key fields (including Many to Many, One to One, etc.) would take in an ID.

If you agree, I also wanted to get a general understanding of how much time that would take as well. I forked the repo and have been experimented with it to see what I can do to provide this feature myself, but I'm not very confident that I can do it since the codebase is so large and I am just learning it.

Thanks again!

**Comment by jstacoder** [comment]
I’ve been looking at similar things lately regarding `nested_fields`  and I really like your idea. Most of the code that uses that value is in `graphene_django_extras.converters` and deals with converting model fields to graphql fields, if you had more questions I could possibly help

**Comment by atomboulian** [comment]
Hey @jstacoder, glad you like it. I figured there were some people out there who could also benefit from this approach. I checked out some of your other contributions to this library. Thanks for your contributions and for responding to this issue.

Yes, I was also noticing `graphene_django_extras.converters`. Perhaps I can start with finding all the classes calling the converters to pass in the boolean. I added more to the test_project and I'm to set a trace as I make a GraphQL call to a serializer mutation. Do you think these are good starting points? Do you have any other recommendations? Thanks again!

**Comment by jstacoder** [comment]
Really because of how things are encapsulated, I think you’ll only need to change things inside of the converters.py file, most of the functions (if they relate to a sql foreignKey ie: ManyToManyField) currently use the `nested_fields` Boolean to either create a dynamic type from the relationship (if `nested_fields` is True) or just return a field with type ID (if it’s False) and that’s just the Boolean you define on the meta, so you would just need to make the parts that say
```python
    if nested_fields:
``` 
to something like 
```python 
    if field_name in nested_field:
``` 
to make it work like you want. 
I’m just not 100% sure about what “`field_name`” would be in that context, but that shouldn’t be to though to find

**Comment by eamigo86** [comment]
Hello @atomboulian and @jstacoder, and many thanks for the good ideas and the contributions you have made to this library. I am delighted that it has been helpful :exclamation::exclamation::exclamation: 

The @jstacoder 's suggestion is valid, but this conditional would only be used in **_conventers.py_** and other minor changes would have to be made in other files so that everything works as expected.

I can make the changes in a while and upload them, but I would not have time to test them properly, could you help me (a little more) and then try to tell me if it works as you expect?

**Comment by eamigo86** [comment]
Hi again, please test the last [alpha](https://github.com/eamigo86/graphene-django-extras/releases/tag/v0.3.8-alpha4) version, to test this functionality and tell me if it works as expected.

Thank you very much again.
 :+1:

**Comment by atomboulian** [comment]
Awesome!!! Thank you for such a quick turnaround. I will test it out and let you know within a couple of days!

**Comment by atomboulian** [comment]
Was able to fix that and other errors by changing the all_directives:

```
all_directives = tuple(default_directives) + date_directives + list_directives + numbers_directives + string_directives


def get_all_directives():
    return all_directives
```

The get_all_directives() was assuming that the directives were callable, and they aren't.

**Comment by atomboulian** [comment]
(Also, default_directives was a list instead of a tuple.)

**Comment by eamigo86** [comment]
Hi @atomboulian, sorry for that, I just did a push again, please try [this](https://github.com/eamigo86/graphene-django-extras/releases/tag/v0.3.8-alpha5)

**Comment by atomboulian** [comment]
Sorry I had to write some other features before circling back on creating our nested mutations.

I can verify that this is working well! Thank you very much! 👍

**Comment by IdemenB** [comment]
> All other Foreign Key fields (including Many to Many, One to One, etc.) would take in an ID.

Dear @atomboulian , could you provide a very basic sample code (of Serializer and Mutation classes)  and a sample query where you pass the ID of an already existing many to many related instance while creating/updating a model instance? Including overwriting the .create() method of the ModelSerializer I've tried all for no success...
